### ISSUE TITLE
$ rosrun jetbot_ros jetbot_motors.py doesn't work

### ISSUE THREAD

**Issue by mantues** [dusty-nv/jetbot_ros#17]
Installing jetbot-ros on the L4T r32.2 image after successfully installing jetbot_ros and ROS Melodic. Testing command rosrun jetbot_ros jetbot_motors.py, the error message below occurs after  processing. I would appreciate your assistance. 

i had run : sudo usermod -aG i2c $USER(user name)

error is below

Traceback (most recent call last):
  File "/home/jetbot/workspace/catkin_ws/src/jetbot_ros/scripts/jetbot_motors.py", line 75, in <module>
    motor_driver = Adafruit_MotorHAT(i2c_bus=1)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 231, in __init__
    self._pwm = PWM(addr, debug=False, i2c=i2c, i2c_bus=i2c_bus)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 57, in __init__
    self.i2c = get_i2c_device(address, i2c, i2c_bus)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 23, in get_i2c_device
    return I2C.get_i2c_device(address, busnum=i2c_bus)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 64, in get_i2c_device
    return Device(address, busnum, i2c_interface, **kwargs)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 97, in __init__
    self._bus = Adafruit_PureIO.smbus.SMBus(busnum)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_PureIO/smbus.py", line 105, in __init__
    self.open(bus)
  File "/home/jetbot/.local/lib/python2.7/site-packages/Adafruit_PureIO/smbus.py", line 130, in open
    self._device = open('/dev/i2c-{0}'.format(bus), 'r+b', buffering=0)
IOError: [Errno 13] Permission denied: '/dev/i2c-1'

**Comment by mantues** [comment]
it was solved after reboot
