### ISSUE TITLE
Error no 121 IOError at ~$ rosrun jetbot_ros jetbot_motors.py

### ISSUE THREAD

**Issue by Vernieface** [dusty-nv/jetbot_ros#36]
Observation:
# file string is: /home/vern/workspace...
Rather than: /home/nvidia/workspace... 

Terminal Session text follows: 
vern@JetBotAI:~$ rosrun jetbot_ros jetbot_motors.py
Traceback (most recent call last):
  File "/home/vern/workspace/catkin_ws/src/jetbot_ros/scripts/jetbot_motors.py", line 75, in <module>
    motor_driver = Adafruit_MotorHAT(i2c_bus=1)
  File "/home/vern/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_MotorHAT_Motors.py", line 231, in __init__
    self._pwm = PWM(addr, debug=False, i2c=i2c, i2c_bus=i2c_bus)
  File "/home/vern/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 59, in __init__
    self.setAllPWM(0, 0)
  File "/home/vern/.local/lib/python2.7/site-packages/Adafruit_MotorHAT/Adafruit_PWM_Servo_Driver.py", line 95, in setAllPWM
    self.i2c.write8(self.__ALL_LED_ON_L, on & 0xFF)
  File "/home/vern/.local/lib/python2.7/site-packages/Adafruit_GPIO/I2C.py", line 114, in write8
    self._bus.write_byte_data(self._address, register, value)
  File "/home/vern/.local/lib/python2.7/site-packages/Adafruit_PureIO/smbus.py", line 268, in write_byte_data
    self._device.write(data)
IOError: [Errno 121] Remote I/O error
vern@JetBotAI:~$

**Comment by santaimpersonator** [comment]
If you are using the SparkFun kit, refer to this response: https://github.com/dusty-nv/jetbot_ros/issues/37#issuecomment-868492714
